### ISSUE TITLE
Create a Kafka sink

### ISSUE THREAD

**Issue by benbromhead** [shotover/shotover-proxy#1008]
Initial sink will only need to support a shotover instance per Kafka broker
May need to support message routing to the right partitions later on down the track, but V1 might not need to.

**Comment by rukai** [comment]
Initial implementation in https://github.com/shotover/shotover-proxy/pull/1042
Lets keep this open till we are happy with the implementation

**Comment by rukai** [comment]
further work tracked in https://github.com/shotover/shotover-proxy/issues/1214
