### ISSUE TITLE
Evaluate supporting different key stores

### ISSUE THREAD

**Issue by benbromhead** [shotover/shotover-proxy#1034]
Currently we support AWS KMS and PKCS (sp?)

Do we want or need to support others?

**Comment by conorbros** [comment]
Google Cloud KMS: https://cloud.google.com/security-key-management
Azure Key Vault: https://azure.microsoft.com/en-us/products/key-vault

**Comment by rukai** [comment]
Since we are not actively working on the protect transform I'm closing this in favor of a single protect transform issue https://github.com/shotover/shotover-proxy/issues/676
