### ISSUE TITLE
Cassandra source closes socket

### ISSUE THREAD

**Issue by benbromhead** [shotover/shotover-proxy#107]
In writing a set of integration tests. Cassandra-rs will fail to connect to shotover configured with a Cassandra source, while cqlsh will connect succesfully.

After a quick look at wireshark, it appears that the cassandra-rs driver (a wrapper around the c/c++ datastax one) tries a few unsupported protocol version, which fail or get downgraded. Cassandra itself wont shutdown the tcp connection, whereas shotover will causeing the driver to error out. 

Given Cassandra supports this behaviour (as broken as it seems), shotover needs to support this. Protocol version errors shouldn't cause us to drop the connection.

**Comment by Claude-at-Instaclustr** [comment]
Testing works locally, now trying to get automated build to work.
