### ISSUE TITLE
Introduce cargo-make

### ISSUE THREAD

**Issue by conorbros** [shotover/shotover-proxy#1288]
Now that we have a fairly complicated setup of integration tests and benchmarks, it makes sense to include a tool to make it easier for ourselves and newcomers to the project.

https://github.com/sagiegurari/cargo-make

**Comment by rukai** [comment]
What would be the advantages of `cargo-make`?
So far we've been following the [xtask approach](https://github.com/matklad/cargo-xtask) and I think its been working well for us.

**Comment by rukai** [comment]
I think this issue was resolved by improving the windsock UX so that we dont need to hide it from the developer. https://github.com/shotover/shotover-proxy/pull/1481
Feel free to reopen if you think theres still problems here that need solving.
