### ISSUE TITLE
TuneableConsistencyScatter Cassandra tests

### ISSUE THREAD

**Issue by conorbros** [shotover/shotover-proxy#1296]
https://docs.shotover.io/shotover-blog/docs/transforms.html#tuneableconsistencyscatter 

Docs demonstrate TuneableConsistencyScatter can be used with Cassandra but a quick look at the code it seems to only support Redis? Need to add some tests for this.

**Comment by rukai** [comment]
TuneableConsistencyScatter was removed in https://github.com/shotover/shotover-proxy/pull/1577
