### ISSUE TITLE
Improve performance of writing to sink outgoing connections

### ISSUE THREAD

**Issue by rukai** [shotover/shotover-proxy#1471]
From looking at a profiler we spend significantly more time writing to the sink socket to the DB than we do writing to the source socket going to the client.
![image](https://github.com/shotover/shotover-proxy/assets/5120858/1803328e-1ddc-4326-b8fd-08598dbfbb8f)
the sink writev is 33% of execution time while the source writev is only 10% of execution time

Furthermore I've observed that limiting the connection to the client to be written one message at a time increases the time spent writing to the source socket as similar to the time spent writing to the sink socket.

So from this I am concluding that in order to improve latency and throughput we need to be batching our messages sent to the sink socket like we do for the source socket.
Implementation wise this will be a lot of work and take some initial refactorings.
The steps required are:
- [x] Rewrite the connection logic for `transforms/cassandra/connection.rs` to send and receive a Vec<Message> instead of a `Message`
- [ ] Rewrite the connection logic for `transforms/util/cluster_connection_pool.rs` to send and receive a Vec<Message> instead of a `Message`
- [ ] Rewrite single sink transforms to send messages in batches
- [ ] Rewrite the cluster sink transforms to first determine routes for messages without touching the connections and then afterwards collect all messages going to a single host into a single batch and then send all batches.

Consider also adding connection pooling for sinks that dont yet support it, so far RedisSinkCluster is the only one to support it. This might get us similar wins at higher connection counts, hard to verify without actually trying it though.

**Comment by benbromhead** [comment]
Sounds like this is worth pursuing.

**Comment by benbromhead** [comment]
Given that we are introducing some degree of batching and asynchronicity to the network connections (well more so in this area). Would it be worth at least a basic "what-if" investigation of using some io_uring networking primitives?

I had looked into it a while back (years) and generally came to the conclusion that the rust ecosystem around it wasn't particularly mature, especially around Tokio. Is this a worthwhile checkpoint to take another look. I imagine that we would still need to make a number of the above changes to support the full speed, but given that this is a set of changes where we might end up "have the engine out of the car already".... might be worth taking a gander.

**Comment by rukai** [comment]
IIRC there is a bit of a mismatch between the design of tokio and io-uring beyond just the implementation being immature.
I also dont know of any serious projects that make use of tokio-uring.
I think its definitely worth experimenting with in the future though.

But I think we should follow this issue to completion first since:
* I believe this issue should take a week to implement, while I think it would take at least a month to get tokio-uring going.
* I believe this issue would improve the performance of a shotover based on tokio-uring as it would give more opportunities to combine syscalls.
* with this issue implemented first we can form a proper comparison between what io-uring and regular sockets are capable of.

**Comment by benbromhead** [comment]
Ok cool. Let's address this first and park io_uring for later.

**Comment by rukai** [comment]
I've completed the planned the swap to sending Vec<Message> instead of Message for KafkaSinkCluster and found no noticeable improvement to benchmarks or flamegraph allocation.
So I think that my guess here that swapping the sinks to write in vec's would reduce time spent writing is incorrect.
That said I think we should still go ahead with the move to the new Connection type as it also: improves error handling + sets us up to use force_run_chain.
Maybe in the future we should attempt to swap Connection to not send in batches and see how that affects code complexity + performance. Once we have the new connection type in place it should be easy to try that out.
