### ISSUE TITLE
Improve benchmarking infrastructure

### ISSUE THREAD

**Issue by rukai** [shotover/shotover-proxy#248]
Currently we have benchmarks running in CI but we dont really have a good way to view the results and be notified of regressions.
We should look to further improving this in our current infrastructure.

But we should also look into ways to get more stable results, possibly by:
* Using something with more stable performance than github actions
* making our benchmarks more stable
   + could write benchmarks that fluctuate less
   + could give our existing benchmarks more leeway before they report a regression

**Comment by conorbros** [comment]
Did that PR close this or is there more to do?

**Comment by rukai** [comment]
Yeah, still more to do, at the very least we need to set reasonable limits so we dont get spammed by useless benchmark comments.

**Comment by rukai** [comment]
I'm closing this as we have gotten false positives to reasonable state.
