### ISSUE TITLE
Validate topology.yaml

### ISSUE THREAD

**Issue by rukai** [shotover/shotover-proxy#254]
Things we want to check:
* <s>every transform chain ends in a terminating transform</s> - complete
* <s>a terminating transform is not followed by a non-terminating transform</s> - complete
* transforms are compatible with each other e.g. RedisTimestampTagger -> CassandraDestination would be bad I think?

**Comment by conorbros** [comment]
How should we determine which transforms are invalid with other ones? I was thinking we could specify with two arrays for each transform which transforms are invalid when in front or behind.

**Comment by rukai** [comment]
I'm closing this since transform compatiblity was largely resolved by https://github.com/shotover/shotover-proxy/issues/520
