### ISSUE TITLE
Tee fixes

### ISSUE THREAD

**Issue by rukai** [shotover/shotover-proxy#281]
Currently we only have an integration tests that use ConsistencyBehaviour::IGNORE

**Comment by conorbros** [comment]
Tee should only be handling write requests. Currently `redis-cluster-dr` has a `QueryTypeFilter` that removes the read queries, we should instead integrate this directly into Tee so users don't have to remember to use the filter every time.

- [ ] Integrate `QueryTypeFilter: Read` directly with `Tee`
- [ ] Add integration tests that use ConsistencyBehaviour::FAIL and ConsistencyBehaviour::LOG
