### ISSUE TITLE
Upstream FuturesOrdered::prepend

### ISSUE THREAD

**Issue by rukai** [shotover/shotover-proxy#285]
## Describe the bug
We should not be vendoring random library code, instead lets upstream our custom FuturesOrdered::prepend method to https://github.com/rust-lang/futures-rs

**Comment by conorbros** [comment]
Update on this: I've opened a PR on futures-rs. Once it's merged we can use that instead and close this.

**Comment by rukai** [comment]
Closed by https://github.com/shotover/shotover-proxy/pull/698
