### ISSUE TITLE
Cannot use QueryCounter properly

### ISSUE THREAD

**Issue by conorbros** [shotover/shotover-proxy#335]
## Describe the bug
QueryCounter cannot be used with Redis chains because every Redis message gets put into the message wrapper as unknown. 

## To Reproduce
1. Create a chain with a Redis destination and QueryCounter. null-redis should suffice for this.
2. Send a query e.g. "SET foo bar", "GET foo"
3. Check the metrics  at http://localhost:9001 and observe the QueryCounter metric still at 0

## Expected behaviour
The RedisSource should have a similar option to the Cassandra one to turn on or off query processing.

An integration test for QueryCounter should be added to `observability_int_tests.rs`

**Comment by rukai** [comment]
This issue refers to problems that were solved by the removal of MessageDetails.
