### ISSUE TITLE
rename *_failed_request metrics

### ISSUE THREAD

**Issue by rukai** [shotover/shotover-proxy#424]
The redis_cluster_failed_request metric only records error messages received from the destination server.
Requests failing due to internal shotover errors are not recorded.

We should either:
* Rename it to redis_cluster_server_error_messages_received
* Change it to record every possible reason a request could fail

This also applies to all similar metrics in other transforms.

**Comment by conorbros** [comment]
See https://github.com/shotover/shotover-proxy/pull/410#discussion_r769187782

We should instead have them named  "failed_requests" and add a tag "transform" => *transform_name*

**Comment by rukai** [comment]
Yes, we should do that as well as one of the choices I described.

**Comment by conorbros** [comment]
I'd add that we need to document the metrics to this ticket too.
