### ISSUE TITLE
Fix stray shotover processes

### ISSUE THREAD

**Issue by rukai** [shotover/shotover-proxy#436]
Happened to come across this during my holiday.

![image](https://user-images.githubusercontent.com/5120858/146920533-10b1b6da-574f-433b-923b-1d88a8cf5b84.png)
https://docs.rs/command-group/latest/command_group/

Might solve our problem of stray shotover processes staying alive in our integration tests.

**Comment by rukai** [comment]
The suggested fix didnt work, it appears that parent and child already share a process group id.

But I can at least easily reproduce the problem by adding a panic here:
![image](https://user-images.githubusercontent.com/5120858/148161561-6318ac38-8fd6-4d64-a4be-0f1fc26a3f52.png)

**Comment by conorbros** [comment]
If child processes are already in the process group, what's the usecase for that crate?

**Comment by rukai** [comment]
Oh it actually does the opposite.
It sets the child process to have a different id.
https://github.com/watchexec/command-group/blob/main/src/stdlib/unix.rs
https://linux.die.net/man/2/setsid

I'll just solve this with a Drop impl
