### ISSUE TITLE
Add Cassandra Bloom filter indexing capabilities as a transform

### ISSUE THREAD

**Issue by Claude-at-Instaclustr** [shotover/shotover-proxy#438]
## Description of Feature

Cassandra Bloom filter index requires that columns be combined to make a Bloom filter and that the Bloom filter be stored in a blob column in the database.  This feature should apply a transform to specific table and columns such that any insert/update on those columns are merged into a Bloom filter and the Bloom filter column updated.

In addition, queries on the table will modify the where clause such that any column included in the bloom filter is removed and the value added to a query Bloom filter and that the "Bloom filter column = query Bloom filter" is added to the where clause.  False positives will need to be removed from solution returned by the query.

## Description of Solution

Create a transform for Bloom filters on Cassandra

### Identify table and columns
The transform will only run on tables that have Bloom filters enabled so the transform configuration must identify the following

* Identify the fully qualified table name.
* Identify the columns that are added to the Bloom filter. (called Bloom filter items - BFI in the documentation below)
* Identify the Bloom filter Column (called BFC in documentation below)
* Describe the "Shape" of the filter (number of bits and number of hashes).

#### Potential issues

1. Fully qualified table name works when Cassandra has not been issues a `use <keyspace>` command.  Not sure how to track the execution of `use <keyspace>`.
2. The number of bits specified in the Shape must match the number of bits specified when the Bloom filter index was created.  There is no check for this.

### Requirements
1. - Populate the bloom filter column on insert / update.
  1.1 - If all BFI columns are not available on update, retrieve columns from table to build a proper Bloom filter or retrieve existing Bloom filter and merge them. (Need to discuss proper strategy)
2. - Populate the bloom filter column on query 
  2.1 - Extract WHERE clause segments that contain BFI to create a Bloom filter.
  2.2 - Add to the "BFC = BloomFilter" to the WHERE clause.
  2.3 - Remove BFI WHERE clause segments from the query
3. - Remove false positives from the query solution
  3.1 - Add BFI to SELECT clause if not already there
  3.2. - Verify that returned values in the BFI SELECT clause segments match the BFI  values in the original WHERE clause segments.  Any results that do not match are dropped.
  3.3 - Remove any BFI SELECT clause segments that were added.   

## Additional context
Possible algorithms

### Insert Algorithm
```
create an empty Bloom filter of the proper Shape.
for any BFI in INSERT
  Hash BFI value and add to Bloom filter.
add "BFC=Bloom filter" to the INSERT clause
execute insert
```

### Update Algorithm
```
create an empty Bloom filter of the proper Shape.
for any BFI in UPDATE
   Hash BFI value and add to Bloom filter.
if any BFI values are not included in update execute one of the update resolution strategies below
add "BFC=Bloom filter" to the UPDATE clause
execute update
```

#### Resolution strategies.

The issue is that the Bloom filter must contain the values for all the populated BFI columns in the final row.  if any BFI is specified then all populated BFI must be specified.  If at least one BFI column is specified and any BFI columns are not specified in the update we will not know if that is because the BFI columns were not updated or were never populated.  There are three possible workarounds:
 1. Request the unspecified BFI from the existing database row, update the Bloom filter and proceed with the update.
 2. Request the Bloom filter from the existing database, merge that with the newly created one and update the table with the result.
 3. Modify the index engine so that a request can be made to update the stored Bloom filter by merging in a second Bloom filter.

Strategies 2 and 3 depend on the property of Bloom filters that allows the merging of multiple filters into a single filter that has all the search properties of the original filters.  The issue that arises is that we will end up with filters that have both the original as well as the updated BFI values for the BFI that were specified in the update.

There are pros and cons for each of the above.

| Strategy | Pro | Con | Workaround |
|------------|------|-------|-----------------|
| 1  | Ensures complete Bloom filter after update | May add significant time to processing as multiple columns may need to be requested |  none |
| 2  | Ensures complete Bloom filter after update | This will result in filters that have old data in them and thus a higher false positive rate. | It should be possible to create a task to read the data from the table and update the Bloom filter in the background.  This will keep the filter up to date and clean. |
| 3 | Faster than 1 or 2 as no additional queries have to be executed. | Requires rework of index implementation as well as investigation into custom index functions.  This will result in filters that have old data in them and will yield a higher false positive rate. | It should be possible to create a task to read the data from the table and update the Bloom filter in the background.  This will keep the filter up to date and clean. |

### Query Algorithm

```
create an empty Bloom filter of the proper Shape.
for any BFI in WHERE clause
   Hash BFI value and add to Bloom filter.
   Remove BFI from WHERE clause.
   if BFI not in SELECT clause add BFI to SELECT clause
add "BFC = Bloom filter" to the WHERE clause
execute query
// filter results
for each result
   if BFI column does not match BFI value in original WHERE clause drop the result.
   filter result columns down to only those columns specified in the original SELECT clause.
return results
```

**Comment by Claude-at-Instaclustr** [comment]
# proposed YAML file structure
```
  - BloomingCassandra
     table:
          keyspace: "keyspace"
          name:  "tablename"
          shape:
               - bits:  15 
               - funcs : 3
          hashFunction: "hashFunctionName"
          bloom : "filterColumnName"
          columns:
              - columnName1
              - columnName2
              - columnName3
              ...
              - columnNameN
     
     table:
           ...  
```

## Notes

1. Each table that is being processed has a table entry.
2. `bits` is the number of bits in the bloom filter
3. `funcs` is the number of hashing functions for each filter
4. `hashFunction` specifies what has will be used.  If not specified Murmur hash will be used.  All configurations must use the same hash for the table or the queries will not work.
5. `bloom` entry is the BFC from earlier documentation.
6. `columns` enumerates the BFI from earlier documentation, order does not matter.

**Comment by Claudenw** [comment]
# Insert Strategy if all columns are not available.

If all the columns are not available in the update the missing columns will be populated by executing a query to retrieve the missing columns and populating the filter correctly.  Issues: Overhead of extra query.

## Other options :

- Create a server side merge function that gets called when a partial update occurs.  
    - Issues: hard to distinguish between complete and partial update
    - requires server side function code,  
    - filters may become highly saturated leading to poor performance for queries.
- Create a server side function that is called  by Shotover when Shotover detects a change.  
    - Issues: requires server side function code,  
    - filters may become highly saturated leading to poor performance for queries.
- Have Shotover request the existing filter and update it on partial change.
    - Issues: Overhead of extra query, 
    - filters may become highly saturated leading to poor performance for queries.

**Comment by benbromhead** [comment]
Some initial thoughts:
- `USE KEYSPACE` is issued on a per tcp session basis, the transform will therefor see any USE KEYSPACE messages issued and be able to persist that in it's own struct which will exist for the life of the tcp session.
-  Might need to add to the description something along the lines of `Queries that don't need to use the BFI to be resolved will be passed on unmodified`. 
- Should we store "shape" information in a C* table somewhere (not the table, but a table)?
- Update / recalculation tools for batch updating data are likely to be outside of scope for shotover itself (e.g. we won't bake that into the main shotover executable), but it might be worth publishing a set of helper utilities that cover this. There are plenty of other cases where we will want to do that (e.g. fixing consistency issues from say the redis replication feature).
- With the potential update resoultion approaches... we need to thinking about read before write consistency issues (what if we have someone updating the same BF), 
- With highly saturated filters, can we log or warn on this and have doco on how to fix this (e.g. playing with the shape)?

**Comment by Claude-at-Instaclustr** [comment]
Thinking about storing shape.  It seems to me that we will, in future, have
multiple transforms that share the properties across different client
sidecar implementations.  Shape for the BFI is an example.  The criteria is
that there is a configuration option, but that option must be the same for
all clients.  To my mind this means we need one location to edit to change
those options.  We could put this in a table somewhere or something
similar, but I think we need a general solution.
