### ISSUE TITLE
Cassandra parser does not support "DELETE <column> FROM <keyspace>.<table> WHERE <col1>=<val1>"

### ISSUE THREAD

**Issue by Claudenw** [shotover/shotover-proxy#444]
## Describe the bug
If a Cassandra delete contains a column to delete the parser fails silently.

executing 
`CassandraCodec::parse_query_string( "DELETE col1 from keyspace.tbl WHERE col3=3", &hash_map );`
fails to parse the `"DELETE col1 from keyspace.tbl WHERE col3=3"` but returns a constructed `ParsedCassandraQueryString`.  The error is not displayed during tests, and the resulting `ParsedCassandraQueryString` has only the namespace value set.

## To Reproduce
```
#[test]
fn test_parse_delete_column_string() {
        let query_str = "DELETE col1 from keyspace.tbl WHERE col3=3";
        let hash_map: HashMap<String,Vec<String>> = HashMap::new();
        let query = CassandraCodec::parse_query_string( query_str, &hash_map);
        let colmap = query.colmap.unwrap();
        let namespace = query.namespace.unwrap();
        let projection = query.projection.unwrap();
        println!( "colmap {:?}", colmap );
        assert_eq!( colmap.len(), 0  );
        println!( "namespace {:?}", namespace );
        assert_eq!( namespace.len(), 2);
        assert_eq!( namespace[0], "keyspace");
        assert_eq!( namespace[1], "tbl");
        println!( "projection {:?}", projection );
        assert_eq!( projection.len(), 0 );

        print!( "ast {:?}", query.ast );
    }
...

## Configuration
Added above test to `cassandra_protocol_tests` in `cassandra_codec.rs`

### Topology
none.


## Expected behaviour
The system should be able to parse the Cassandra delete query.  

## Systems and Version:
 - OS Ubuntu 20.04.3 LTS (Focal Fossa)
 - Shotover Version "main branch"
 - Version of 3rd party software: n/a

## Additional context

**Comment by Claudenw** [comment]
The issue seems to be in the sqlparser::parser::Parser:parse_delete function (as expected).  Based on Andy Grove's comments https://github.com/sqlparser-rs/sqlparser-rs/blob/main/docs/custom_sql_parser.md we will have to write a custom parser that delegates to the generic one.  Creating a new CQLDialect will not be sufficient.

**Comment by rukai** [comment]
Thanks for raising this.
I've personally run into a lot of issues from shotover pretending CSQL is SQL as well.
Delegating to the generic parser is not something I considered but might be good idea.
Another approach would be to write a new CSQL parser from scratch which might end up having its own benefits.
Someone will need to do a deep dive into this area and come up with a design + prototype.

**Comment by benbromhead** [comment]
When I first looked into this, I spent a little bit of time seeing if support for generating a parser from antlr definition files was available for rust. It might be worth lookin at this again as the cassandra project helpfully provides some antly definitions for CQL3:

https://github.com/apache/cassandra/tree/trunk/src/antlr

**Comment by rukai** [comment]
Closed by https://github.com/shotover/shotover-proxy/pull/661
