### ISSUE TITLE
The Cassandra codec does not set the QueryType correctly

### ISSUE THREAD

**Issue by Claudenw** [shotover/shotover-proxy#447]
## Describe the bug
The Cassandra codec always set the query type to QueryType::Read.  It should set it to Write for Update and Insert commands.

## To Reproduce
1. execute an insert or update query.
2. examine the QueryType in the MessageDetails.
...

## Configuration
n/a
### Topology
n/a
Please include any configuration for setting up services such as `docker-compose` that the `topology.yaml` depends on.

## Expected behaviour
For insert and update queries the QueryType should be set to Write

**Comment by conorbros** [comment]
Can we close this? @Claude-at-Instaclustr

**Comment by Claude-at-Instaclustr** [comment]
Yes
