### ISSUE TITLE
Handle duplicate stream_id in unordered_cluster_connection_pool.rs

### ISSUE THREAD

**Issue by rukai** [shotover/shotover-proxy#459]
This code currently assumes stream id is unique but that is definitely not the case, it is valid for stream id to always be the same value

Anyone can start on this now, as its an improvement even outside of the context of the message details rewrite.

**Comment by conorbros** [comment]
I can take this if you aren't

**Comment by rukai** [comment]
that would be great!

**Comment by conorbros** [comment]
Closing as we no longer have `UnorderedClusterConnectionPool`
