### ISSUE TITLE
Cassandra Request throttling

### ISSUE THREAD

**Issue by benbromhead** [shotover/shotover-proxy#543]
## Is your feature request related to a problem? Please describe.
A number of Instaclustr customers are interested in being able to enforce a global request throttling for Cassandra clusters. Database traffic should be able to be throttled on per request (per query) basis.  

## Describe the solution you'd like
Shotover should be able to enforce only a certain number of requests/queries per second globally across all connections. If the number of requests entering shotover exceeds the configured value, an error is returned to the client (similar to Cassandras own backpressure mechanism).

**Comment by benbromhead** [comment]
**Critical requirements**
- Support request throttling across all connections for a given transform chain
- Support proper handling of the cluster discovery process client drivers do (e.g. rewrite peer table queries)
- Support throwing Overloaded errors back to the client driver https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v3.spec#L968

**Nice to have requirements, but not important**
- C* cluster support (shotover can route to different upstream nodes)
- Different traffic quotas for different connection attributes (e.g. different C* users have different quotas)
- Shotover maintains a global view of total request traffic across a fleet of shotover proxies (e.g. a cluster wide request quota)

The preferred testing model will be shotover running in standalone proxy mode, the end production deployment model will be colocated with each Cassandra node

**Comment by benbromhead** [comment]
For the moment...

**Out of scope**
- Including queries inside a single batch query

**Comment by benbromhead** [comment]
Some useful background reading on the existing back pressure mechanisms in C* -> https://cassandra.apache.org/_/blog/Improving-Apache-Cassandras-Front-Door-and-Backpressure.html 

We will likely use the built in protocol back pressure messages to get clients to back off.

**Comment by conorbros** [comment]
TODO:
- [ ] Support request throttling across all connections for a given transform chain
- [ ] https://github.com/shotover/shotover-proxy/issues/546
- [ ] Including queries inside a single batch query
