### ISSUE TITLE
Parse cassandra BATCH messages

### ISSUE THREAD

**Issue by rukai** [shotover/shotover-proxy#563]
Batch messages contains queries just like QUERY messages but there is currently no way for shotover transforms to process them.

~~If possible, an implementation where CassandraOperation::Query and CassandraOperation::Batch are combined into a single variant would give really nice transform UX.
we would disambiguate between them by checking the length of the queries Vec.
if queries.len() == 1 then its a QUERY message otherwise its a BATCH message.
There is a bunch of complicated flags and stuff going on in the BATCH message protocol though so this might not be possible.~~

Didnt end up taking that approach.
Instead we currently have the half finished `QueryIterator` abstraction.
Just need to finish it off.

**Comment by benbromhead** [comment]
Can we close this out now?
