### ISSUE TITLE
Convert batch over CassandraOperation::Query into regular CassandraOperation::Batch

### ISSUE THREAD

**Issue by rukai** [shotover/shotover-proxy#575]
cassandra batches can be parsed server side or client side.
That is cassandra will accept batches sent over the BATCH protocol as documented but it will also accept a `BEGIN BATCH ... APPLY BATCH` query string sent over the QUERY protocol

for the C++ driver you can use the BATCH protocol via https://docs.rs/cassandra-cpp/0.17.2/cassandra_cpp/struct.Session.html#method.execute_batch
But if you provide execute with a `BEGIN BATCH ...` then it will send the batch string over the QUERY protocol https://docs.rs/cassandra-cpp/0.17.2/cassandra_cpp/struct.Session.html#method.execute

To allow transforms to transparently handle both types, `CassandraOperation::Query`s that contain batch messages should be converted into regular `CassandraOperation::Batch`

Make sure to extend the batch int tests to test both cases.

**Comment by benbromhead** [comment]
See #563

**Comment by rukai** [comment]
This is a separate issue to #563
We could combine them if you wanted though.
