### ISSUE TITLE
Update Documentation to list lib requirements for build

### ISSUE THREAD

**Issue by Claude-at-Instaclustr** [shotover/shotover-proxy#594]
## Describe the bug
 * `cargo test` will fail if 
    * pcap is not installed.
    * cassandra lib
    * uv lib is not installed 
 * pcap is not mentioned in the build documentation

## To Reproduce
1. start with system without pcap_lib installed.
2. clone code
3. execute `cargo test`
...

## Expected behaviour

Expect build to succeed

## Systems and Version:
 - OS Ubuntu 20.04.4 LTS
 - Shotover Version dev

**Comment by conorbros** [comment]
I'm having trouble recreating this. What steps did you need to follow to get it working?

**Comment by Claude-at-Instaclustr** [comment]
I got it to fail by starting with a plain Vanilla Ubuntu install.

**Comment by conorbros** [comment]
What steps did you do to get it working?

**Comment by rukai** [comment]
Setup steps for ubuntu are now documented at https://github.com/shotover/shotover-proxy/blob/main/docs/src/dev-docs/setting-up-linux.md
