### ISSUE TITLE
Add Cassandra session level tracking

### ISSUE THREAD

**Issue by Claude-at-Instaclustr** [shotover/shotover-proxy#620]
PR  #598 (Use cql3 parser) brings with it the ability to process non-SQL commands.

One of the commands `USE <keyspace>`  changes the state of the connection on the server side.  In order for Shotover to properly process commands after the `USE` command it must track the keyspace named in the command and apply it to parsed names where the keyspace is permitted but not provided.  Effectively, the `USE` command sets a default keyspace.

This change should figure out how to track sessions (not requests) between the client and the server so that the default namespace, and similar values, can be tracked across the requests.  The session ID may be different from the stream ID found in the Cassandra frame itself.  Part of this issue is to determine if that is the case or not.

The end result is that we will have the ability to store and clear session data so that data that crosses requests can be handled efficiently and consistently across the code base.

**Comment by rukai** [comment]
we ended up taking a somewhat different approach but the proper handling of use statements was implemented by https://github.com/shotover/shotover-proxy/pull/806
