### ISSUE TITLE
Remove CQLStatement::get_table_name(CassandraStatement)

### ISSUE THREAD

**Issue by Claude-at-Instaclustr** [shotover/shotover-proxy#629]
The merge of #598  will bring in the `CQLStatement::get_table_name` function.  It should be replaced with `CassandraStatement.get_table_name` function once that is implemented in the CQL3 parser.  That change is tracked as https://github.com/shotover/rust-cql3-parser/issues/20

**Comment by rukai** [comment]
This is already resolved within https://github.com/shotover/shotover-proxy/pull/661
And since this occured entirely within forks we can close this issue already
