### ISSUE TITLE
Cannot connect to shotover on redis cluster using lettuce.io client

### ISSUE THREAD

**Issue by carrie-instaclustr** [shotover/shotover-proxy#656]
## Describe the bug
Cannot use the lettuce.io client to connect to shotover installed on a Redis cluster.

## To Reproduce
1. Have tried the below code block with on clusters with and without authentication, and with and without SSL. Have modified code depending on cluster configuration (taking out SSL for example).
```java
       final RedisURI redisUri = RedisURI.Builder.redis("<ip>") 
                .withPort(6378)
                .withAuthentication("<username>", "<password>")
                .withSsl(true)
                .withVerifyPeer(false)
                .build();
```
2.  Connecting directly to the redis port works, however trying to go via the shotover port results in 
```
Exception in thread "main" io.lettuce.core.RedisConnectionException: Unable to establish a connection to Redis Cluster
	at io.lettuce.core.cluster.RedisClusterClient.lambda$assertInitialPartitions$26(RedisClusterClient.java:922)
	at io.lettuce.core.cluster.RedisClusterClient.get(RedisClusterClient.java:941)
	at io.lettuce.core.cluster.RedisClusterClient.assertInitialPartitions(RedisClusterClient.java:921)
	at io.lettuce.core.cluster.RedisClusterClient.connect(RedisClusterClient.java:398)
	at io.lettuce.core.cluster.RedisClusterClient.connect(RedisClusterClient.java:375)
	at com.mycompany.app.App.main(App.java:63)
Caused by: io.lettuce.core.cluster.topology.DefaultClusterTopologyRefresh$CannotRetrieveClusterPartitions: Cannot retrieve cluster partitions from [redis://<user>:****************@<ip>:6378]

Details:
	[redis://<username>:****************@<ip>:6378]: Unable to connect to [<ip>:6378]: NOAUTH Authentication required (cached)
```
3. Connecting to the same cluster works using the redis-cli and the jedis client.
  
### Topology

3 node DC + 3 node dc in DR

// Your topology.yaml file
```yaml
sources:
  redis_prod:
    Redis: {batch_size_hint: 4, listen_addr: '0.0.0.0:6378', connection_limit: 20000,
      hard_connection_limit: true}
chain_config:
  redis_chain:
  - Tee:
      behavior: Ignore
      buffer_size: 10000
      chain:
      - QueryTypeFilter: {filter: Read}
      - Coalesce:
          max_behavior:
            CountOrWait: [2000, 100]
      - Tee:
          buffer_size: 100
          timeout_micros: 10000
          chain:
          - QueryCounter: {name: DR_chain}
          - RedisSinkCluster:
              first_contact_points: ['44.232.82.142:6379']
      - 'Null'
  - QueryCounter: {name: Main_chain}
  - RedisClusterPortsRewrite: {new_port: 6378}
  - RedisSinkCluster:
      first_contact_points: ['3.216.108.90:6379']
source_to_chain_mapping: {redis_prod: redis_chain}
```

Please include any configuration for setting up services such as `docker-compose` that the `topology.yaml` depends on.

## Expected behaviour
Expect to be able to connect to shotover via the lettuce.io client.

## Systems and Version:
 - OS
 - Shotover Version: 0.1.3
 - Version of 3rd party software e.g. Cassandra, Redis: Lettuce client: 6.1.8.RELEASE

**Comment by rukai** [comment]
I believe the issue is because shotover does not support the HELLO command.
https://redis.io/commands/hello/
Implementing support for the hello command should be enough to resolve the issue.

Lettuce makes full use of the hello command so we will need to handle all of these features:
* protvar
* auth
* setname

**Comment by rukai** [comment]
This is closed because I believe I have fixed the issue.
Please try again with the latest master and reopen if theres still issues.
