### ISSUE TITLE
Cassandra CPP Driver Test portability

### ISSUE THREAD

**Issue by benbromhead** [shotover/shotover-proxy#726]
## Is your feature request related to a problem? Please describe.
Currently we leverage the Datastax CPP driver for integration testing of our C* functionality. This is good and fine, however building the CPP driver can be challenging depending on what distro and what version of the distro you are on.

## Describe the solution you'd like
Let's make the CPP driver tests and dependency optional for anyone trying to build shotover locally. We should then opt-in and still build / run the CPP driver tests on PRs / merges to main. This would make getting started with shotover dev much easier for folks.

## Describe alternatives you've considered
We could improve the resiliency of building the CPP driver, but I've struggled to land packaging changes upstream in the CPP project.

**Comment by rukai** [comment]
This is a really good idea. :+1:
