### ISSUE TITLE
CassandraSinkCluster dynamic port handling

### ISSUE THREAD

**Issue by rukai** [shotover/shotover-proxy#773]
Currently we hardcode the port 9042 everywhere, but we should handle the port dynamically from the config and system.peers_v2 results.

**Comment by conorbros** [comment]
`system.local` also returns different results on different versions. 

Do you think we should try and remember what release version a node is running or just attempt both queries everytime?

I'm leaning towards the latter for simplicity, if we run into perf issues could revisit.

**Comment by rukai** [comment]
yeah thats a good point, it is a little tricky.

Another alternative is to do `SELECT * FROM system.local` and then use the metadata to get port fields from system.local if they exist.
Dealing with metadata does also complicate things though.

I dont think any of these approaches stands out as the clear best way, feel free to pick any that works out well enough.

**Comment by conorbros** [comment]
How does the metadata complicate things? 

My first thoughts are it seems pretty simple to check what fields are there and just grab them.

**Comment by rukai** [comment]
Yeah, its not too bad, just need to loop and check strings, go for it if you think its a good solution!
