### ISSUE TITLE
specify benches to run with the bench_against_master_local script

### ISSUE THREAD

**Issue by conorbros** [shotover/shotover-proxy#790]
The ability to only run a selected benchmark(s) with this script would be very useful e.g.

`./bench_against_master_local redis/cluster_tls`

**Comment by rukai** [comment]
Usually when performing performance work its better to set a baseline of main branch once.
That way we can compare multiple runs of our new branch against it without having to rerun the main branch benches every time.
So I propose we close this in favor of that workflow?

Or maybe just remove the "good first issue" and assign the issue to yourself if you would personally like to see the work done?
I think it best if we keep the "good first issue" tag for work that will upskill in rust for our incoming newstarters.

**Comment by rukai** [comment]
Closing as we intend to remove this script https://github.com/shotover/shotover-proxy/pull/1621
