### ISSUE TITLE
Cassandra integration testing

### ISSUE THREAD

**Issue by benbromhead** [shotover/shotover-proxy#93]
Like the redis integration tests, we need to implement a set of Cassandra tests from a chosen rust Cassandra driver.

**Comment by rukai** [comment]
ah, we havent done this, we want an extensive cassandra test suite similar to what we have for redis.

**Comment by conorbros** [comment]
I think I can close this as we have got our Cassandra int test suite to a good and comprehensive state. Any other thoughts before I do so? @rukai @benbromhead

**Comment by rukai** [comment]
I havent checked it over for comprehensiveness but what we have now is definitely a huge improvement over before. I'm fine with closing.
