### ISSUE TITLE
Murmur3token size panic

### ISSUE THREAD

**Issue by yuzhouchen-instaclustr** [shotover/shotover-proxy#949]
Hit this panic while running cassandra-stress:
```
Dec 01 11:16:57 ip-192-168-9-209 shotover-proxy[85091]: thread 'Shotover-Proxy-Thread' panicked at 'range end index 56 out of range for slice of length 55', /root/.cargo/git/checkouts/cdrs-tokio-2745bf6890ae9470/546b7b3/cassandra-protocol/src/token.rs:32:17
```

This should actually be part of token aware routing, but will make it as an individual issue for its high priority.

It's blocking stress test.

**Comment by rukai** [comment]
It looks like the input to Murmer3Token::generate needs to have a length
 that is a multiple of 8 but we pass it something that is not a multiple
 of 8. Not sure if we need to guarantee that our input is multiple of 8 or if Murmer3Token::generate needs to handle any value.
