### ISSUE TITLE
shotover is executing queries on nodes in other racks

### ISSUE THREAD

**Issue by yuzhouchen-instaclustr** [shotover/shotover-proxy#977]
When running the Cassandra testing tool cassandra-stress, I can see shotover sending out EXECUTE requests to nodes in racks other than its own, which is not supposed to happen by design. 

The table I'm using has a composite primary key, so I also tested it with a single primary key, I can confirm I'm seeing the same phenomenon in both cases.

I've also tested this with my own Java client and I can see it happening as well, which means this unlikely a cassandra-stress issue, the Cassandra node in other racks being hit isn't necessarily a replica either.

This appears to be quite random, repeating the same query with the same PK does not always yield the same result (i.e. same trace)

**Comment by rukai** [comment]
Assuming a properly generated token distribution: if the keyspace being queried has a replica count less than the number of nodes per rack then sometimes the destination will end up outside of the rack.
Can you confirm that the keyspace you are querying has a replica count higher than or equal to the number of nodes per rack?

**Comment by rukai** [comment]
closed by https://github.com/shotover/shotover-proxy/pull/1384
