### ISSUE TITLE
Expose a metric that would measure the time taken from receiving a message and sending it back

### ISSUE THREAD

**Issue by yuzhouchen-instaclustr** [shotover/shotover-proxy#984]
Currently the metric shotover_chain_latency does not take into account the time it takes to encode each message, it would be better if we can include that time as well.

**Comment by conorbros** [comment]
Just to clarify, you mean include the time it takes to decode the message on arrival, process through the chain and encode at the end?

**Comment by rukai** [comment]
I investigated this yesterday/today and have a design that I'll go ahead with:
* at the decode codecs: include timestamp in Message (or maybe Messages)
* at the sink encode codec: histogram!(sink_to_source_latency, sink=name_of_sink)
* at the source encode codec: histogram!(source_to_sink_latency, source=name_of_source)

**Comment by rukai** [comment]
completed in https://github.com/shotover/shotover-proxy/pull/1395
