### ISSUE TITLE
why do you use Kafka

### ISSUE THREAD

**Issue by MaryLilian** [shotover/shotover-proxy#996]
Hi, I am reading your project and I love this project
I have a question, why do you choose Kafka in your project instead of others like RabbitMQ or ZeroMQ, are there any special feature but others dont have it. Can you share me about it. I am wondering when I should choose Kafka instead of others like RabbitMQ or ZeroMQ

**Comment by benbromhead** [comment]
Hi @MaryLilian, Kafka was previously chosen to demonstrate leveraging a stream processing system and it's the one I have experience with. There is no reason why we couldn't also have a similar RabbitMQ and ZeroMQ transform as well in the project. For what it's worth we ended up removing the Kafka transform for the moment as it wasn't actively used and bitrotting, however it is very much on our long term roadmap. 

If you want to contribute a new Kafka, RabbitMQ or ZeroMQ publishing transform to the project that would be awesome! To get started I would recommend reading the following:

- https://docs.shotover.io/transforms.html
- https://docs.shotover.io/contributing.html
-  https://github.com/shotover/shotover-proxy/blob/d3eb22d491f08569d712aaa078e2655690530dbb/shotover-proxy/src/transforms/tee.rs#L125-L177

The Tee transform sends messages over a Tokio multi-producer, single-consumer queue and would most likely match the required logic to support an external queue/streaming system you mentioned.
